local sub = ubermenu:add_submenu({ title = "Community Server Management" })
	local sub1 = sub:add_submenu({ title = "Capture the Flag" })
		sub1:add_item({ title = "Arx Novena",             func = function() openConsole("/srvcmd NextMap 1456") end })
		sub1:add_item({ title = "Bella Omega",            func = function() openConsole("/srvcmd NextMap 1573") end })
		sub1:add_item({ title = "Bella Omega NS",         func = function() openConsole("/srvcmd NextMap 1551") end })
		sub1:add_item({ title = "Blueshift",              func = function() openConsole("/srvcmd NextMap 1543") end })
		sub1:add_item({ title = "Canyon Crusade Revival", func = function() openConsole("/srvcmd NextMap 1514") end })
		sub1:add_item({ title = "Crossfire",              func = function() openConsole("/srvcmd NextMap 1462") end })
		sub1:add_item({ title = "Dangerous Crossing",     func = function() openConsole("/srvcmd NextMap 1538") end })
		sub1:add_item({ title = "Drydock",                func = function() openConsole("/srvcmd NextMap 1457") end })
		sub1:add_item({ title = "Hellfire",               func = function() openConsole("/srvcmd NextMap 1560") end })
		sub1:add_item({ title = "Icecoaster",             func = function() openConsole("/srvcmd NextMap 1554") end })
		sub1:add_item({ title = "Katabatic",              func = function() openConsole("/srvcmd NextMap 1447") end })
		sub1:add_item({ title = "Perdition",              func = function() openConsole("/srvcmd NextMap 1555") end })
		sub1:add_item({ title = "Permafrost",             func = function() openConsole("/srvcmd NextMap 1534") end })
		sub1:add_item({ title = "Raindance",              func = function() openConsole("/srvcmd NextMap 1516") end })
		sub1:add_item({ title = "Stonehenge",             func = function() openConsole("/srvcmd NextMap 1522") end })
		sub1:add_item({ title = "Sunstar",                func = function() openConsole("/srvcmd NextMap 1523") end })
		sub1:add_item({ title = "Tartarus",               func = function() openConsole("/srvcmd NextMap 1512") end })
		sub1:add_item({ title = "Temple Ruins",           func = function() openConsole("/srvcmd NextMap 1493") end })
		sub1:add_item({ title = "Terminus",               func = function() openConsole("/srvcmd NextMap 1553") end })
		sub1:add_item({ title = "Blues",               	  func = function() openConsole("/srvcmd NextMapName TrCTF-Blues") end })
		sub1:add_item({ title = "Periculo",               func = function() openConsole("/srvcmd NextMapName TrCTF-Periculo") end })
		sub1:add_item({ title = "Incidamus",              func = function() openConsole("/srvcmd NextMapName TrCTF-Incidamus") end })

	local sub1 = sub:add_submenu({ title = "Arena" })
		sub1:add_item({ title = "Air Arena",              func = function() openConsole("/srvcmd NextMap 1495") end })
		sub1:add_item({ title = "Fraytown",               func = function() openConsole("/srvcmd NextMap 1545") end })
		sub1:add_item({ title = "Hinterlands",            func = function() openConsole("/srvcmd NextMap 1533") end })
		sub1:add_item({ title = "Lava Arena",             func = function() openConsole("/srvcmd NextMap 1498") end })
		sub1:add_item({ title = "Undercroft",             func = function() openConsole("/srvcmd NextMap 1546") end })
		sub1:add_item({ title = "Walled In",              func = function() openConsole("/srvcmd NextMap 1497") end })
		sub1:add_item({ title = "Whiteout",               func = function() openConsole("/srvcmd NextMap 1544") end })

	local sub1 = sub:add_submenu({ title = "Blitz" })
		sub1:add_item({ title = "Arx Novena",             func = function() openConsole("/srvcmd NextMap 2566") end })
		sub1:add_item({ title = "Bella Omega",            func = function() openConsole("/srvcmd NextMap 1550") end })
		sub1:add_item({ title = "Blueshift",              func = function() openConsole("/srvcmd NextMap 1552") end })
		sub1:add_item({ title = "Canyon Crusade Revival", func = function() openConsole("/srvcmd NextMap 1549") end })
		sub1:add_item({ title = "Crossfire",              func = function() openConsole("/srvcmd NextMap 1542") end })
		sub1:add_item({ title = "Drydock",                func = function() openConsole("/srvcmd NextMap 2599") end })
		sub1:add_item({ title = "Hellfire",               func = function() openConsole("/srvcmd NextMap 1561") end })
		sub1:add_item({ title = "Katabatic",              func = function() openConsole("/srvcmd NextMap 2598") end })

	local sub1 = sub:add_submenu({ title = "Capture and Hold" })
		sub1:add_item({ title = "Canyon Crusade Revival", func = function() openConsole("/srvcmd NextMap 1548") end })
		sub1:add_item({ title = "Drydock Night",          func = function() openConsole("/srvcmd NextMap 1530") end })
		sub1:add_item({ title = "Katabatic",              func = function() openConsole("/srvcmd NextMap 1521") end })
		sub1:add_item({ title = "Outskirts 3P",           func = function() openConsole("/srvcmd NextMap 1526") end })
		sub1:add_item({ title = "Raindance",              func = function() openConsole("/srvcmd NextMap 1528") end })
		sub1:add_item({ title = "Sulfurcove",             func = function() openConsole("/srvcmd NextMap 1535") end })
		sub1:add_item({ title = "Tartarus",               func = function() openConsole("/srvcmd NextMap 1537") end })

	local sub1 = sub:add_submenu({ title = "Rabbit" })
		sub1:add_item({ title = "Crossfire",              func = function() openConsole("/srvcmd NextMap 1464") end })
		sub1:add_item({ title = "Inferno",                func = function() openConsole("/srvcmd NextMap 1491") end })
		sub1:add_item({ title = "Nightabatic",            func = function() openConsole("/srvcmd NextMap 1494") end })
		sub1:add_item({ title = "Outskirts",              func = function() openConsole("/srvcmd NextMap 1458") end })
		sub1:add_item({ title = "Quicksand",              func = function() openConsole("/srvcmd NextMap 1461") end })
		sub1:add_item({ title = "Sulfur Cove",            func = function() openConsole("/srvcmd NextMap 1496") end })

	local sub1 = sub:add_submenu({ title = "Team Deathmatch" })
		sub1:add_item({ title = "Crossfire",              func = function() openConsole("/srvcmd NextMap 1482") end })
		sub1:add_item({ title = "Drydock Night",          func = function() openConsole("/srvcmd NextMap 1480") end })
		sub1:add_item({ title = "Inferno",                func = function() openConsole("/srvcmd NextMap 1487") end })
		sub1:add_item({ title = "Miasma",                 func = function() openConsole("/srvcmd NextMap 1536") end })
		sub1:add_item({ title = "Nightabatic",            func = function() openConsole("/srvcmd NextMap 1485") end })
		sub1:add_item({ title = "Outskirts",              func = function() openConsole("/srvcmd NextMap 1490") end })
		sub1:add_item({ title = "Quicksand",              func = function() openConsole("/srvcmd NextMap 1484") end })
		sub1:add_item({ title = "Sulfur Cove",            func = function() openConsole("/srvcmd NextMap 1488") end })

	sub:add_separator({})
	sub:add_item({ title = "End Current Map",             func = function() openConsole("/srvcmd EndMap") end })
	sub:add_item({ title = "Skip Warmup",                 func = function() openConsole("/srvcmd StartMap") end })

	sub:add_separator({ title = "Server" })
	sub:add_item({ title = "Send Console Message",        func = function() openConsole("/srvlua Admin.SendConsoleMessageToAllPlayers(\"MESSAGE\")") end })
	sub:add_item({ title = "Send Game Message",           func = function() openConsole("/srvlua Admin.SendGameMessageToAllPlayers(\"MESSAGE\", 2.0)") end })
	sub:add_variable({ title = "Server Login Role", varname = "srvloginrole", default = "mod" })
	sub:add_item({ title = "Login",                       func = function() openConsole("/srvlogin " ..  srvloginrole .. " ") end })

sub = nil
sub1 = nil
